version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.7
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.2
    - 3.11.0
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
  - dependency-name: svelte-preprocess
    versions:
    - 4.7.0
    - 4.7.1
  - dependency-name: imagemin-svgo
    versions:
    - 9.0.0
  - dependency-name: rollup
    versions:
    - 2.41.0
    - 2.41.2
    - 2.45.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 18.0.0
  - dependency-name: clean-css
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: preact
    versions:
    - 10.5.13
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
